sudo: false
language: java
jdk:
  - openjdk8
  - openjdk11
script:
  - ./build.sh
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then cd violations-gradle-plugin-example && bash ./gradlew check -PdiffFrom=$TRAVIS_PULL_REQUEST_BRANCH -PdiffTo=$TRAVIS_BRANCH ; fi'
after_script:
  - find -name TEST* -exec cat {} \;
notifications:
  email: false
